Repository apecloud/kbcli, pull requests merged in 2023-11, with the labels that each got.

#17 chore: adjust workflow
  .github/utils/issue_prerelease.sh
  .github/utils/issue_release.sh
  .github/utils/release_gitlab.sh
  .github/workflows/cicd-pull-request.yml
  .github/workflows/cicd-push.yml
  .github/workflows/codeql.yml
  .github/workflows/pull-request-stats.yml
  .github/workflows/pull-request-user-interaction.yaml
  .goreleaser.yaml
  Makefile
Labels: size/XL

#18 chore: add release kbcli workflow
  .github/utils/release_gitlab.sh
  .github/workflows/release-kbcli.yml
Labels: size/XL

#20 chore: support kbcli milestone and release-notes
  .github/utils/generate_release_notes.py
  .github/utils/issue_release.sh
  .github/workflows/issues-move.yml
  .github/workflows/milestone-set.yaml
  .github/workflows/milestoneclose.yml
  .github/workflows/release-notes.yaml
Labels: size/XL

#21 chore: fix upload codecoverage error
  .github/utils/utils.sh
  .github/workflows/cicd-pull-request.yml
  .github/workflows/cicd-push.yml
Labels: size/XS

#24 fix: add issue_prerelease.sh
  .github/utils/issue_prerelease.sh
Labels: size/L

#27 fix: fix make kbcli-doc fail in CI
  Makefile
Labels: size/XS

#28 feat: cherry-pick #5794 in Kubeblocks
  go.mod
  go.sum
  pkg/cmd/cluster/create.go
  pkg/cmd/cluster/dataprotection.go
Labels: size/M

#32 chore: Revert "feat: cherry-pick #5801 in Kubeblocks"
  docs/user_docs/cli/cli.md
  docs/user_docs/cli/kbcli.md
  docs/user_docs/cli/kbcli_cluster_create.md
  docs/user_docs/cli/kbcli_cluster_create_orioledb.md
  docs/user_docs/cli/kbcli_cluster_create_qdrant.md
  pkg/cmd/auth/login.go
  pkg/cmd/cli.go
  pkg/cmd/context/cloud_context.go
  pkg/cmd/context/cloud_context_test.go
  pkg/cmd/organization/cloud_organization.go
  pkg/cmd/organization/organization.go
Labels: size/L

#38 chore: add code owner and modify github issue assigness
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/improvement-request.md
Labels: size/XS

#39 chore: fix make-test fail
  pkg/action/edit_test.go
  pkg/action/patch_test.go
Labels: size/XS

#37 chore: add logs dir to store kbcli log
  pkg/action/suite_test.go
  pkg/cmd/cli.go
  pkg/types/types.go
  pkg/util/log.go
  pkg/util/util.go
Labels: size/S

#41 feat: only stop kubeblocks when kubeblocks version is specified
  pkg/cmd/kubeblocks/upgrade.go
Labels: size/M

#49 fix: modify kubeblocks pkg version
  go.mod
  go.sum
  pkg/cloudprovider/k3d.go
  pkg/cloudprovider/provider.go
  pkg/cmd/builder/template/component_wrapper.go
  pkg/cmd/builder/template/util.go
  pkg/cmd/cluster/connect.go
  pkg/cmd/kubeblocks/config_test.go
  pkg/cmd/kubeblocks/install.go
  pkg/cmd/kubeblocks/install_test.go
  pkg/cmd/kubeblocks/upgrade_test.go
  pkg/cmd/playground/init.go
  pkg/cmd/playground/init_test.go
  pkg/cmd/playground/util.go
  pkg/util/helm/helm_test.go
Labels: size/L

#52 chore: support continuous backup and restore
  pkg/cmd/cluster/create.go
  pkg/cmd/cluster/dataprotection.go
Labels: size/S

#57 chore: move init addon repo in index cmd
  docs/user_docs/cli/kbcli_plugin_index_add.md
  pkg/cmd/addon/index.go
  pkg/cmd/plugin/index.go
Labels: size/S

#61 fix: contexts index out of range
  pkg/cmd/auth/login.go
Labels: size/XS

#60 chore: add UT for index cmd
  pkg/cmd/addon/index.go
  pkg/cmd/addon/index_test.go
Labels: size/M

#58 chore: fix KB version
  go.mod
  go.sum
Labels: size/XS

#59 fix: fix kbcli addon index update always latest
  pkg/util/git.go
Labels: size/M

#65 chore: cluster connect to replica whose pod role label is set as primary
  pkg/cluster/helper.go
Labels: size/S

#45 feat: use opsrequst to achieve backup and restore
  pkg/action/template/opsrequest_template.cue
  pkg/cmd/cluster/dataprotection.go
  pkg/cmd/cluster/dataprotection_test.go
  pkg/cmd/dataprotection/backup.go
  pkg/cmd/dataprotection/restore.go
Labels: size/L

#68 fix: kbcli cluster connect use root credential
  docs/user_docs/cli/kbcli_cluster_create_llm.md
  pkg/cmd/auth/login.go
  pkg/cmd/cluster/connect.go
Labels: size/M

#69 chore: fix usage and error msg
  docs/user_docs/cli/kbcli_cluster_create_llm.md
  docs/user_docs/cli/kbcli_clusterdefinition_list-service-reference.md
  pkg/cmd/cluster/create.go
  pkg/cmd/clusterdefinition/list_service_reference.go
Labels: size/S

#72 chore: switchover ops with component definition api
  pkg/cmd/cluster/operations.go
  pkg/cmd/cluster/operations_test.go
  pkg/testing/fake.go
  pkg/types/types.go
Labels: size/L

#81 chore: only create specified components when creating cluster
  docs/user_docs/cli/kbcli_cluster_create.md
  pkg/cmd/cluster/create.go
  pkg/cmd/cluster/create_test.go
Labels: size/M
