Repository apecloud/kbcli, pull requests merged in 2023-12, with the labels that each got.

#87 chore: remove hack for creating clusters
  pkg/cluster/charts/apecloud-mysql-cluster.tgz
  pkg/cluster/charts/kafka-cluster.tgz
  pkg/cluster/charts/llm-cluster.tgz
  pkg/cluster/charts/mongodb-cluster.tgz
  pkg/cluster/charts/postgresql-cluster.tgz
  pkg/cluster/charts/redis-cluster.tgz
  pkg/cluster/charts/xinference-cluster.tgz
  pkg/cmd/cluster/create.go
Labels: size/M

#88 feat: cluster create set labels
  docs/user_docs/cli/kbcli_cluster_create.md
  pkg/action/template/cluster_template.cue
  pkg/cluster/charts/apecloud-mysql-cluster.tgz
  pkg/cluster/charts/kafka-cluster.tgz
  pkg/cluster/charts/llm-cluster.tgz
  pkg/cluster/charts/mongodb-cluster.tgz
  pkg/cluster/charts/postgresql-cluster.tgz
  pkg/cluster/charts/redis-cluster.tgz
  pkg/cluster/charts/xinference-cluster.tgz
  pkg/cmd/cluster/create.go
Labels: size/S

#90 feat: cpu & memory oversell
  docs/user_docs/cli/kbcli_cluster_create.md
  pkg/cluster/charts/apecloud-mysql-cluster.tgz
  pkg/cluster/charts/kafka-cluster.tgz
  pkg/cluster/charts/llm-cluster.tgz
  pkg/cluster/charts/mongodb-cluster.tgz
  pkg/cluster/charts/postgresql-cluster.tgz
  pkg/cluster/charts/redis-cluster.tgz
  pkg/cluster/charts/xinference-cluster.tgz
  pkg/cmd/cluster/create.go
Labels: size/M

#91 fix: req & limit point to same resource
  pkg/cluster/charts/apecloud-mysql-cluster.tgz
  pkg/cluster/charts/kafka-cluster.tgz
  pkg/cluster/charts/llm-cluster.tgz
  pkg/cluster/charts/mongodb-cluster.tgz
  pkg/cluster/charts/postgresql-cluster.tgz
  pkg/cluster/charts/redis-cluster.tgz
  pkg/cluster/charts/xinference-cluster.tgz
  pkg/cmd/cluster/create.go
Labels: size/XS

#92 feat: support "kbcli backuprepo delete"
  docs/user_docs/cli/cli.md
  docs/user_docs/cli/kbcli_backuprepo.md
  pkg/cluster/charts/apecloud-mysql-cluster.tgz
  pkg/cluster/charts/kafka-cluster.tgz
  pkg/cluster/charts/llm-cluster.tgz
  pkg/cluster/charts/mongodb-cluster.tgz
  pkg/cluster/charts/postgresql-cluster.tgz
  pkg/cluster/charts/redis-cluster.tgz
  pkg/cluster/charts/xinference-cluster.tgz
  pkg/cmd/backuprepo/backuprepo.go
  pkg/cmd/backuprepo/delete.go
  pkg/cmd/backuprepo/delete_test.go
  pkg/testing/factory.go
Labels: size/L

#80 feat: support addon install/uninstall/upgrade
  docs/user_docs/cli/cli.md
  docs/user_docs/cli/kbcli_addon.md
  pkg/cmd/addon/addon.go
  pkg/cmd/addon/index.go
  pkg/cmd/addon/index_test.go
  pkg/cmd/addon/install.go
  pkg/cmd/addon/install_test.go
  pkg/cmd/addon/uninstall.go
  pkg/cmd/addon/upgrade.go
  pkg/cmd/addon/upgrade_test.go
  pkg/testing/fake.go
  pkg/types/types.go
Labels: size/XL

#98 chore: sub cmd private to public
  Makefile
  docs/user_docs/cli/kbcli_addon_install.md
  docs/user_docs/cli/kbcli_addon_search.md
  docs/user_docs/cli/kbcli_addon_uninstall.md
  docs/user_docs/cli/kbcli_addon_upgrade.md
  docs/user_docs/cli/kbcli_backuprepo_delete.md
  pkg/cluster/builtin_charts.go
  pkg/cluster/charts/apecloud-mysql-cluster.tgz
  pkg/cluster/charts/clickhouse-cluster.tgz
  pkg/cluster/charts/kafka-cluster.tgz
  pkg/cluster/charts/llm-cluster.tgz
  pkg/cluster/charts/milvus-cluster.tgz
  pkg/cluster/charts/mongodb-cluster.tgz
  pkg/cluster/charts/neon-cluster.tgz
  pkg/cluster/charts/postgresql-cluster.tgz
  pkg/cluster/charts/qdrant-cluster.tgz
  pkg/cluster/charts/redis-cluster.tgz
  pkg/cluster/charts/weaviate-cluster.tgz
  pkg/cluster/charts/xinference-cluster.tgz
  pkg/cluster/cluster_chart.go
  pkg/cmd/cluster/create_subcmds.go
  pkg/cmd/cluster/create_subcmds_test.go
Labels: size/L

#99 fix: kafka create no pvc
  pkg/cluster/charts/apecloud-mysql-cluster.tgz
  pkg/cluster/charts/clickhouse-cluster.tgz
  pkg/cluster/charts/kafka-cluster.tgz
  pkg/cluster/charts/llm-cluster.tgz
  pkg/cluster/charts/milvus-cluster.tgz
  pkg/cluster/charts/mongodb-cluster.tgz
  pkg/cluster/charts/neon-cluster.tgz
  pkg/cluster/charts/postgresql-cluster.tgz
  pkg/cluster/charts/qdrant-cluster.tgz
  pkg/cluster/charts/redis-cluster.tgz
  pkg/cluster/charts/weaviate-cluster.tgz
  pkg/cluster/charts/xinference-cluster.tgz
  pkg/cmd/cluster/create.go
Labels: size/XS

#103 feat: support to install or upgrade crds for 0.8 version
  pkg/cluster/charts/apecloud-mysql-cluster.tgz
  pkg/cluster/charts/clickhouse-cluster.tgz
  pkg/cluster/charts/kafka-cluster.tgz
  pkg/cluster/charts/llm-cluster.tgz
  pkg/cluster/charts/milvus-cluster.tgz
  pkg/cluster/charts/mongodb-cluster.tgz
  pkg/cluster/charts/neon-cluster.tgz
  pkg/cluster/charts/postgresql-cluster.tgz
  pkg/cluster/charts/qdrant-cluster.tgz
  pkg/cluster/charts/redis-cluster.tgz
  pkg/cluster/charts/weaviate-cluster.tgz
  pkg/cluster/charts/xinference-cluster.tgz
  pkg/cmd/kubeblocks/install.go
  pkg/cmd/kubeblocks/upgrade.go
  pkg/cmd/kubeblocks/util.go
  pkg/util/util.go
Labels: size/M

#104 chore: update embed charts
  pkg/cluster/charts/apecloud-mysql-cluster.tgz
  pkg/cluster/charts/clickhouse-cluster.tgz
  pkg/cluster/charts/kafka-cluster.tgz
  pkg/cluster/charts/llm-cluster.tgz
  pkg/cluster/charts/milvus-cluster.tgz
  pkg/cluster/charts/mongodb-cluster.tgz
  pkg/cluster/charts/neon-cluster.tgz
  pkg/cluster/charts/postgresql-cluster.tgz
  pkg/cluster/charts/qdrant-cluster.tgz
  pkg/cluster/charts/redis-cluster.tgz
  pkg/cluster/charts/weaviate-cluster.tgz
  pkg/cluster/charts/xinference-cluster.tgz
Labels: size/XS

#106 feat: support custom ops
  docs/user_docs/cli/cli.md
  docs/user_docs/cli/kbcli.md
  docs/user_docs/cli/kbcli_cluster.md
  go.mod
  go.sum
  pkg/action/template/cluster_operations_template.cue
  pkg/cluster/charts/apecloud-mysql-cluster.tgz
  pkg/cluster/charts/clickhouse-cluster.tgz
  pkg/cluster/charts/kafka-cluster.tgz
  pkg/cluster/charts/llm-cluster.tgz
  pkg/cluster/charts/milvus-cluster.tgz
  pkg/cluster/charts/mongodb-cluster.tgz
  pkg/cluster/charts/neon-cluster.tgz
  pkg/cluster/charts/postgresql-cluster.tgz
  pkg/cluster/charts/qdrant-cluster.tgz
  pkg/cluster/charts/redis-cluster.tgz
  pkg/cluster/charts/weaviate-cluster.tgz
  pkg/cluster/charts/xinference-cluster.tgz
  pkg/cluster/helper.go
  pkg/cmd/accounts/create.go
  pkg/cmd/addon/upgrade.go
  pkg/cmd/backuprepo/common.go
  pkg/cmd/backuprepo/create.go
  pkg/cmd/backuprepo/update.go
  pkg/cmd/class/create.go
  pkg/cmd/class/list.go
  pkg/cmd/class/utils.go
  pkg/cmd/cli.go
  pkg/cmd/cluster/cluster.go
  pkg/cmd/cluster/create.go
  pkg/cmd/cluster/create_test.go
  pkg/cmd/cluster/dataprotection.go
  pkg/cmd/cluster/dataprotection_test.go
  pkg/cmd/cluster/describe_ops.go
  pkg/cmd/cluster/operations.go
  pkg/cmd/cluster/operations_test.go
  pkg/cmd/clusterdefinition/describe.go
  pkg/types/types.go
  pkg/util/flags/flags.go
  pkg/util/flags/schema_to_flags.go
  pkg/util/util.go
Labels: size/XL

#107 fix: upgrade kb failed
  pkg/cluster/charts/apecloud-mysql-cluster.tgz
  pkg/cluster/charts/clickhouse-cluster.tgz
  pkg/cluster/charts/kafka-cluster.tgz
  pkg/cluster/charts/llm-cluster.tgz
  pkg/cluster/charts/milvus-cluster.tgz
  pkg/cluster/charts/mongodb-cluster.tgz
  pkg/cluster/charts/neon-cluster.tgz
  pkg/cluster/charts/postgresql-cluster.tgz
  pkg/cluster/charts/qdrant-cluster.tgz
  pkg/cluster/charts/redis-cluster.tgz
  pkg/cluster/charts/weaviate-cluster.tgz
  pkg/cluster/charts/xinference-cluster.tgz
  pkg/cmd/kubeblocks/util.go
Labels: size/XS

#108 chore: revert addon cmd
  Makefile
  docs/user_docs/cli/cli.md
  docs/user_docs/cli/kbcli.md
  pkg/cmd/cli.go
Labels: size/S

#101 fix: kb install panic when user have no permission
  pkg/cmd/kubeblocks/kubeblocks_objects.go
  pkg/cmd/kubeblocks/util.go
Labels: size/M

#105 fix: support remember KB image registry config to all addons
  pkg/cmd/addon/addon.go
  pkg/cmd/backuprepo/delete_test.go
  pkg/cmd/cli.go
  pkg/cmd/kubeblocks/install.go
  pkg/cmd/kubeblocks/util.go
  pkg/types/config.go
  pkg/types/types.go
  pkg/util/util.go
Labels: size/M

#110 refactor: update option to split code related to cmd
  pkg/action/patch.go
  pkg/action/patch_test.go
  pkg/cluster/charts/apecloud-mysql-cluster.tgz
  pkg/cluster/charts/clickhouse-cluster.tgz
  pkg/cluster/charts/kafka-cluster.tgz
  pkg/cluster/charts/llm-cluster.tgz
  pkg/cluster/charts/milvus-cluster.tgz
  pkg/cluster/charts/mongodb-cluster.tgz
  pkg/cluster/charts/neon-cluster.tgz
  pkg/cluster/charts/postgresql-cluster.tgz
  pkg/cluster/charts/qdrant-cluster.tgz
  pkg/cluster/charts/redis-cluster.tgz
  pkg/cluster/charts/weaviate-cluster.tgz
  pkg/cluster/charts/xinference-cluster.tgz
  pkg/cmd/addon/addon.go
  pkg/cmd/cluster/update.go
  pkg/cmd/cluster/update_test.go
Labels: size/L

#111 refactor: apiserver address to viper
  docs/user_docs/cli/cli.md
  docs/user_docs/cli/kbcli.md
  pkg/cmd/auth/authorize/authenticator/pkce_authenticator.go
  pkg/cmd/auth/login.go
  pkg/cmd/auth/utils/bindata.go
  pkg/cmd/auth/utils/const.go
  pkg/cmd/cli.go
  pkg/cmd/context/cloud_context.go
  pkg/cmd/context/cloud_context_test.go
  pkg/cmd/context/context.go
  pkg/cmd/organization/cloud_organization_test.go
  pkg/cmd/organization/organization.go
  pkg/types/config.go
Labels: size/L

#113 chore: add configuration and opsrequest for kbcli report subcommand
  pkg/action/template/cluster_operations_template.cue
  pkg/cmd/report/report.go
  pkg/types/types.go
Labels: size/S

#114 fix: do not set default image registry
  pkg/cmd/addon/addon.go
  pkg/cmd/cli.go
Labels: size/XS

#116 fix: fix image.registry env not be persisted
  go.mod
  pkg/cmd/addon/addon.go
  pkg/cmd/cluster/operations.go
  pkg/cmd/kubeblocks/install.go
Labels: size/M

#117 chore: check diff before update chart
  Makefile
  pkg/cluster/charts/apecloud-mysql-cluster.tgz
  pkg/cluster/charts/milvus-cluster.tgz
  pkg/cluster/charts/neon-cluster.tgz
  pkg/cmd/backuprepo/delete.go
Labels: size/S

#119 fix: output redundant config info
  pkg/cmd/cli.go
Labels: size/XS

#121 fix: create-account failed to locate primary pod
  pkg/cluster/helper.go
  pkg/cmd/accounts/base.go
  pkg/cmd/cluster/operations.go
Labels: size/S

#124 chore: add OB cluster as kbcli embed chart
  Makefile
  docs/user_docs/cli/kbcli_cluster_create.md
Labels: size/XS

#126 chore: add ElasticSearch to kbcli embed chart
  Makefile
Labels: size/XS

#127 fix: handle version is nil
  docs/user_docs/cli/kbcli_cluster_create.md
  pkg/cmd/addon/install.go
  pkg/cmd/addon/testdata/kubeblocks/apecloud-mysql/0.8.0-alpha.5.yaml
Labels: size/XS

#129 refactor: account api to public
  pkg/cluster/charts/elasticsearch-cluster.tgz
  pkg/cluster/charts/oceanbase-cluster.tgz
  pkg/cmd/accounts/base.go
  pkg/cmd/accounts/base_test.go
  pkg/cmd/accounts/create.go
  pkg/cmd/accounts/create_test.go
  pkg/cmd/accounts/delete.go
  pkg/cmd/accounts/delete_test.go
  pkg/cmd/accounts/describe.go
  pkg/cmd/accounts/grant.go
  pkg/cmd/accounts/grant_test.go
  pkg/cmd/accounts/list.go
  pkg/cmd/accounts/list_test.go
  pkg/cmd/accounts/revoke.go
  pkg/cmd/cluster/accounts.go
Labels: size/L

#130 chore: fix addon output
  pkg/cmd/addon/index.go
  pkg/cmd/addon/search.go
  pkg/cmd/addon/search_test.go
  pkg/cmd/addon/uninstall.go
  pkg/cmd/addon/upgrade.go
Labels: size/S

#131 feat: create cluster set annotations
  docs/user_docs/cli/kbcli_cluster_create.md
  pkg/cmd/cluster/create.go
Labels: size/S

#132 chore: bump kubeblocks version to v0.8.0-beta.15
  go.mod
  go.sum
  pkg/testing/fake.go
Labels: size/S

#133 bugfix: update lorry exec
  go.mod
  go.sum
  pkg/cmd/accounts/create.go
  pkg/cmd/accounts/delete.go
  pkg/cmd/accounts/describe.go
  pkg/cmd/accounts/grant.go
  pkg/cmd/accounts/list.go
  pkg/cmd/accounts/revoke.go
  pkg/testing/fake.go
Labels: size/M

#135 refactor: public account describe
  pkg/cmd/accounts/describe.go
  pkg/cmd/accounts/describe_test.go
  pkg/cmd/cluster/accounts.go
Labels: size/M

#138 feat: cluster promote use lorry switchover if available
  pkg/cluster/charts/oceanbase-cluster.tgz
  pkg/cmd/cluster/operations.go
  pkg/cmd/cluster/operations_test.go
Labels: size/L

#143 fix: failed to update backup repo
  pkg/cmd/backuprepo/update.go
  pkg/cmd/backuprepo/update_test.go
Labels: size/XS

#141 chore: update kb api
  docs/user_docs/cli/kbcli_dataprotection_restore.md
  go.mod
  go.sum
  pkg/cmd/cluster/create.go
  pkg/cmd/cluster/dataprotection.go
  pkg/cmd/cluster/update.go
  pkg/cmd/dataprotection/restore.go
Labels: size/S

#144 chore: update embed chart
  Makefile
  pkg/cluster/charts/neon-cluster.tgz
  pkg/cluster/charts/oceanbase-cluster.tgz
  pkg/cluster/charts/redis-cluster.tgz
Labels: size/XS

#134 chore: refine help message of 'kbcli backuprepo create'
  docs/user_docs/cli/cli.md
  docs/user_docs/cli/kbcli_backuprepo.md
  docs/user_docs/cli/kbcli_backuprepo_create.md
  pkg/cmd/backuprepo/create.go
Labels: size/S

#145 chore: adjust release kbcli workflow
  .github/workflows/release-create.yml
  .github/workflows/release-kbcli.yml
  .github/workflows/release-version.yml
  pkg/util/util.go
Labels: size/L

#147 chore: fix oceanbase promote
  pkg/cmd/cluster/operations.go
Labels: size/S

#148 chore: push cloud tag
  .github/workflows/release-create.yml
  .github/workflows/release-tag.yaml
Labels: size/M

#149 chore: push tag with latest sha
  .github/workflows/release-tag.yaml
Labels: size/S

#151 fix: connect with wrong role after kb upgrade
  docs/user_docs/cli/kbcli_cluster_create_redis.md
  pkg/cluster/charts/oceanbase-cluster.tgz
  pkg/cluster/charts/redis-cluster.tgz
  pkg/cluster/cluster.go
  pkg/cluster/cluster_chart.go
  pkg/cluster/cluster_test.go
  pkg/cluster/external_charts.go
  pkg/cluster/helper.go
  pkg/cluster/helper_test.go
  pkg/cluster/printer.go
  pkg/cluster/validate.go
  pkg/cmd/bench/pgbench.go
  pkg/cmd/bench/sysbench.go
  pkg/cmd/bench/tpcc.go
  pkg/cmd/bench/tpch.go
  pkg/cmd/bench/ycsb.go
  pkg/cmd/cluster/connect.go
  pkg/cmd/cluster/connect_test.go
  pkg/cmd/cluster/create_subcmds.go
  pkg/cmd/cluster/describe.go
  pkg/cmd/cluster/list_logs.go
  pkg/cmd/cluster/logs.go
Labels: size/L

#153 chore: fix release kbcli tag name
  .github/workflows/release-create.yml
  .github/workflows/release-kbcli.yml
Labels: size/M

#139 chore: fix connect secret error
  pkg/cluster/cluster.go
  pkg/cluster/types.go
  pkg/cmd/cluster/connect.go
  pkg/cmd/cluster/connect_test.go
  pkg/types/types.go
Labels: size/M

#154 chore: send result after release kbcli
  .github/workflows/release-kbcli.yml
Labels: size/S

#155 chore: fix sequence not close
  .github/workflows/release-kbcli.yml
Labels: size/XS

#160 chore: auto update kbcli embed chart changes
  .github/workflows/release-tag.yaml
Labels: size/S

#165 chore: check if primary exists when promote
  pkg/cmd/cluster/operations.go
Labels: size/XS

#156 fix: kbcli connect without secret
  pkg/cluster/cluster.go
  pkg/cmd/cluster/connect.go
Labels: size/M

#167 chore: fix connect show-example
  pkg/cmd/cluster/connect.go
Labels: size/XS

#171 fix: upgrade kb version
  go.mod
  go.sum
Labels: size/XS
