Repository apecloud/kbcli, pull requests merged in 2024-02, with the labels that each got.

#253 fix: driver validate
  pkg/cmd/bench/sysbench.go
  pkg/cmd/bench/tpcc.go
Labels: size/XS

#258 fix: create account crash
  pkg/cmd/accounts/create.go
  pkg/cmd/accounts/delete.go
  pkg/cmd/accounts/describe.go
  pkg/cmd/accounts/grant.go
  pkg/cmd/accounts/list.go
  pkg/cmd/accounts/revoke.go
Labels: size/M

#261 chore: ignore empty jsonData
  pkg/cmd/cluster/create.go
  pkg/cmd/cluster/create_util.go
Labels: size/XS

#270 fix: timeinterval nil
  pkg/cmd/alert/add_receiver.go
Labels: size/S

#271 chore: update kb version to 0.9.0
  .github/workflows/pull-request-check.yml
  go.mod
  go.sum
  pkg/cluster/helper.go
  pkg/cmd/accounts/base.go
  pkg/cmd/builder/template/component_wrapper.go
  pkg/testing/fake.go
Labels: size/M

#272 chore: preflight check kubernetes version 1.20 instead of 1.22
  pkg/cmd/kubeblocks/data/ack_preflight.yaml
  pkg/cmd/kubeblocks/data/eks_preflight.yaml
  pkg/cmd/kubeblocks/data/gke_preflight.yaml
  pkg/cmd/kubeblocks/data/kubeblocks_base_preflight.yaml
  pkg/cmd/kubeblocks/data/tke_preflight.yaml
  pkg/testing/testdata/preflight.yaml
  pkg/util/helm/helm.go
Labels: size/M

#275 chore: update roleprobe test
  pkg/testing/fake.go
Labels: size/XS
