Repository apecloud/kbcli, pull requests merged in 2024-04, with the labels that each got.

#298 feat: adjust configconstraint api (#297)
  go.mod
  go.sum
  pkg/cluster/helper.go
  pkg/cmd/builder/template/helm_helper.go
  pkg/cmd/cluster/config_diff.go
  pkg/cmd/cluster/config_edit.go
  pkg/cmd/cluster/config_observer.go
  pkg/cmd/cluster/config_ops.go
  pkg/cmd/cluster/config_ops_test.go
  pkg/cmd/cluster/config_resource.go
  pkg/cmd/cluster/config_util_test.go
  pkg/cmd/cluster/operations.go
  pkg/cmd/cluster/update.go
  pkg/scheme/install.go
  pkg/testing/client.go
  pkg/testing/fake.go
  pkg/types/types.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: size/L

#299 docs: add a CONTRIBUTING.md file for kbcli repo
  CONTRIBUTING.md
  README.md
Labels: size/M

#311 chore: bot repeat approve
  .github/workflows/auto-approve.yml
Labels: size/XS

#318 chore: compatible sharding and instance
  docs/user_docs/cli/kbcli_cluster_configure.md
  docs/user_docs/cli/kbcli_cluster_edit-config.md
  docs/user_docs/cli/kbcli_cluster_expose.md
  docs/user_docs/cli/kbcli_cluster_hscale.md
  docs/user_docs/cli/kbcli_cluster_restart.md
  docs/user_docs/cli/kbcli_cluster_volume-expand.md
  docs/user_docs/cli/kbcli_cluster_vscale.md
  go.sum
  pkg/action/template/cluster_operations_template.cue
  pkg/cmd/cluster/operations.go
  pkg/cmd/cluster/operations_test.go
Labels: size/L

#320 chore: update sharding ops
  pkg/action/template/cluster_operations_template.cue
Labels: size/S

#321 chore: update restore cmd
  docs/user_docs/cli/kbcli_cluster_create.md
  docs/user_docs/cli/kbcli_cluster_create_kafka.md
  docs/user_docs/cli/kbcli_cluster_create_redis.md
  go.mod
  go.sum
  pkg/cmd/cluster/create.go
Labels: size/L

#317 fix: sample code for the cluster section
  docs/user_docs/cli/kbcli_cluster_configure.md
  pkg/cmd/cluster/config_ops.go
Labels: size/XS

#316 chore: update new monitor api for kbcli (#7015)
  docs/user_docs/cli/kbcli_cluster_create.md
  docs/user_docs/cli/kbcli_cluster_update.md
  go.mod
  go.sum
  pkg/cluster/helper.go
  pkg/cluster/helper_test.go
  pkg/cmd/builder/template/component_wrapper.go
  pkg/cmd/cluster/create.go
  pkg/cmd/cluster/create_test.go
  pkg/cmd/cluster/update.go
  pkg/cmd/cluster/update_test.go
  pkg/cmd/clusterversion/clusterversion.go
  pkg/cmd/clusterversion/set_default.go
  pkg/cmd/clusterversion/set_default_test.go
  pkg/cmd/kubeblocks/status.go
  pkg/cmd/playground/init.go
  pkg/cmd/plugin/plugin.go
  pkg/types/types.go
  pkg/util/breakingchange/upgradehandlerto0.7.go
Labels: size/L, area/user-interaction

#324 chore: prefer using StorageProvider from the dataprotection API group
  docs/user_docs/cli/kbcli_dataprotection_restore.md
  go.mod
  go.sum
  pkg/cmd/backuprepo/common.go
  pkg/cmd/backuprepo/create.go
  pkg/cmd/backuprepo/update.go
  pkg/cmd/cluster/create.go
  pkg/cmd/dataprotection/restore.go
  pkg/testing/fake.go
  pkg/types/types.go
Labels: size/L
