Repository apecloud/kbcli, pull requests merged in 2024-11, with the labels that each got.

#480 chore: support skip helm schema validation
  go.mod
  go.sum
  pkg/cluster/cluster_chart.go
  pkg/cluster/cluster_chart_test.go
  pkg/cmd/cluster/create_subcmds.go
Labels: size/L

#481 chore: support to skip helm schema validattion
  pkg/cluster/cluster_chart.go
  pkg/cmd/cluster/create_subcmds.go
Labels: size/S

#479 chore: cmpd/cmpv list/describe adapt 1.0 api
  docs/user_docs/cli/cli.md
  docs/user_docs/cli/kbcli.md
  pkg/cmd/cli.go
  pkg/cmd/clusterdefinition/describe.go
  pkg/cmd/componentdefinition/componentdefinition_test.go
  pkg/cmd/componentdefinition/componnetdefinition.go
  pkg/cmd/componentdefinition/describe.go
  pkg/cmd/componentdefinition/suite_test.go
  pkg/cmd/componentversion/componentversion.go
  pkg/cmd/componentversion/componentversion_test.go
  pkg/cmd/componentversion/describe.go
  pkg/cmd/componentversion/suite_test.go
Labels: size/XL

#483 chore: cluster create support specify schedulingpolicy
  docs/user_docs/cli/kbcli_cluster_create_apecloud-mysql.md
  docs/user_docs/cli/kbcli_cluster_create_elasticsearch.md
  docs/user_docs/cli/kbcli_cluster_create_kafka.md
  docs/user_docs/cli/kbcli_cluster_create_llm.md
  docs/user_docs/cli/kbcli_cluster_create_mongodb.md
  docs/user_docs/cli/kbcli_cluster_create_mysql.md
  docs/user_docs/cli/kbcli_cluster_create_postgresql.md
  docs/user_docs/cli/kbcli_cluster_create_qdrant.md
  docs/user_docs/cli/kbcli_cluster_create_redis.md
  docs/user_docs/cli/kbcli_cluster_create_xinference.md
  pkg/cmd/cluster/cluster_test.go
  pkg/cmd/cluster/create_subcmds.go
  pkg/cmd/cluster/register_test.go
  pkg/util/util.go
Labels: size/L

#486 chore: support to install 1.0 KB when existing 0.9.2 KB
  Makefile
  docs/user_docs/cli/kbcli_kubeblocks_config.md
  docs/user_docs/cli/kbcli_kubeblocks_describe-config.md
  docs/user_docs/cli/kbcli_kubeblocks_install.md
  docs/user_docs/cli/kbcli_kubeblocks_uninstall.md
  docs/user_docs/cli/kbcli_kubeblocks_upgrade.md
  docs/user_docs/cli/kbcli_report_cluster.md
  docs/user_docs/cli/kbcli_report_kubeblocks.md
  pkg/cmd/backuprepo/create.go
  pkg/cmd/kubeblocks/config.go
  pkg/cmd/kubeblocks/install.go
  pkg/cmd/kubeblocks/install_1.0.go
  pkg/cmd/kubeblocks/install_1.0_test.go
  pkg/cmd/kubeblocks/install_test.go
  pkg/cmd/kubeblocks/status.go
  pkg/cmd/kubeblocks/suite_test.go
  pkg/cmd/kubeblocks/uninstall.go
  pkg/cmd/kubeblocks/uninstall_test.go
  pkg/cmd/kubeblocks/upgrade.go
  pkg/cmd/kubeblocks/upgrade_test.go
  pkg/cmd/report/report.go
  pkg/util/breakingchange/constant.go
  pkg/util/breakingchange/upgradehandlerto0.7.go
  pkg/util/breakingchange/upgrader.go
  pkg/util/conversion/types.go
  pkg/util/helm/helm.go
  pkg/util/util.go
  pkg/util/version.go
  pkg/util/version_test.go
Labels: size/XXL

#490 fix: specifying namespace on ops cmds.
  pkg/cmd/cluster/operations.go
Labels: size/S

#492 chore: fix check upgrade release status
  pkg/cmd/kubeblocks/upgrade.go
  pkg/cmd/kubeblocks/upgrade_test.go
  pkg/util/helm/errors.go
  pkg/util/helm/helm.go
  pkg/util/helm/helm_test.go
Labels: size/L

#494 chore: support to upgrade addon to 1.0 version
  pkg/cmd/addon/install.go
  pkg/cmd/addon/upgrade.go
  pkg/cmd/kubeblocks/install_1.0.go
  pkg/util/util.go
Labels: size/M

#495 chore: cluster stop and start support components
  docs/user_docs/cli/kbcli_cluster_custom-ops.md
  docs/user_docs/cli/kbcli_cluster_start.md
  docs/user_docs/cli/kbcli_cluster_stop.md
  pkg/action/template/cluster_operations_template.cue
  pkg/cmd/cluster/operations.go
  pkg/cmd/cluster/register.go
Labels: size/M

#497 chore: pick etcd to release-1.0
  docs/user_docs/cli/kbcli_cluster_create.md
  pkg/cluster/builtin_charts.go
  pkg/cluster/charts/etcd.tgz
Labels: size/XS

#498 fix: upgrade kb failed because no KB deployment was found.
  pkg/cmd/kubeblocks/install_1.0.go
  pkg/cmd/kubeblocks/install_1.0_test.go
  pkg/cmd/kubeblocks/upgrade.go
Labels: size/M

#454 feat: Support Reconciliation Tracing
  docs/user_docs/cli/cli.md
  docs/user_docs/cli/kbcli.md
  go.mod
  go.sum
  pkg/action/template/trace_template.cue
  pkg/cmd/cli.go
  pkg/cmd/cluster/describe_ops_test.go
  pkg/cmd/trace/chart/objecttree/tree_chart.go
  pkg/cmd/trace/chart/reconciliation_trace_chart.go
  pkg/cmd/trace/chart/richviewport/viewport.go
  pkg/cmd/trace/chart/summary/summary_chart.go
  pkg/cmd/trace/chart/timeserieslinechart/options.go
  pkg/cmd/trace/chart/timeserieslinechart/timeserieslinechart.go
  pkg/cmd/trace/chart/timeserieslinechart/updatehandler.go
  pkg/cmd/trace/create.go
  pkg/cmd/trace/delete.go
  pkg/cmd/trace/list.go
  pkg/cmd/trace/update.go
  pkg/cmd/trace/view.go
  pkg/cmd/trace/watch.go
  pkg/types/types.go
Labels: size/XXL

#500 chore: playground init support specifying k3s and k3d-proxy images.
  docs/user_docs/cli/kbcli_playground_init.md
  pkg/cloudprovider/k3d.go
  pkg/cloudprovider/k3d_test.go
  pkg/cloudprovider/suite_test.go
  pkg/cloudprovider/types.go
  pkg/cmd/cluster/operations.go
  pkg/cmd/cluster/register_test.go
  pkg/cmd/playground/init.go
  pkg/cmd/playground/suite_test.go
Labels: size/L

#504 chore: remove standard chart schema
  pkg/cluster/external_charts.go
  pkg/cluster/register_test.go
  pkg/cluster/testdata/mock-chart-0.1.0.tgz
Labels: size/M
