Repository apecloud/kbcli, pull requests merged in 2024-06, with the labels that each got.

#365 chore: kb install support wait-addons
  docs/user_docs/cli/kbcli_cluster_create_mongodb.md
  docs/user_docs/cli/kbcli_kubeblocks_install.md
  pkg/cmd/kubeblocks/install.go
Labels: size/S

#369 chore: update kb version to 0.9.0-beta.32
  go.mod
  go.sum
  pkg/cmd/cluster/describe_ops.go
  pkg/cmd/cluster/describe_ops_test.go
  pkg/testing/factory.go
  pkg/util/breakingchange/upgradehandlerto0.7.go
Labels: size/M

#372 chore: fix get recoverable time fail
  pkg/cmd/cluster/describe.go
Labels: size/XS

#375 fix: conversion error log (#7532)
  pkg/cmd/cli.go
  pkg/cmd/kubeblocks/upgrade.go
  pkg/util/conversion/types.go
Labels: size/M

#360 docs: fix typos
  docs/user_docs/cli/kbcli_cluster_edit-config.md
  pkg/cmd/cluster/config_edit.go
  pkg/cmd/cluster/errors.go
Labels: size/XS
