Repository apecloud/kbcli, pull requests merged in 2024-10, with the labels that each got.

#451 chore: remove the region check for eks
  pkg/cmd/kubeblocks/data/eks_hostpreflight.yaml
Labels: size/S

#447 feat: check helm release status before kubeblocks upgrade
  pkg/cmd/kubeblocks/upgrade.go
  pkg/cmd/kubeblocks/upgrade_test.go
  pkg/util/helm/helm.go
  pkg/util/helm/helm_test.go
Labels: size/L

#462 chore: fix cluster chart version when auto register
  pkg/cmd/addon/addon.go
Labels: size/XS

#466 fix: fetch kb version from helm release chart before upgrade
  pkg/cmd/kubeblocks/upgrade.go
  pkg/cmd/kubeblocks/upgrade_test.go
  pkg/util/helm/helm.go
  pkg/util/helm/helm_test.go
Labels: size/M

#461 chore: enable rbac by default for elasticsearch (#460)
  docs/user_docs/cli/kbcli_cluster_create_elasticsearch.md
  pkg/cmd/cluster/create_subcmds.go
  pkg/cmd/cluster/create_util.go
  pkg/cmd/cluster/create_util_test.go
Labels: size/M

#467 feat: adapt ops with new api
  docs/user_docs/cli/cli.md
  docs/user_docs/cli/kbcli_cluster.md
  docs/user_docs/cli/kbcli_cluster_configure.md
  docs/user_docs/cli/kbcli_cluster_create_mysql.md
  docs/user_docs/cli/kbcli_cluster_create_postgresql.md
  docs/user_docs/cli/kbcli_cluster_custom-ops.md
  docs/user_docs/cli/kbcli_cluster_edit-config.md
  docs/user_docs/cli/kbcli_cluster_expose.md
  docs/user_docs/cli/kbcli_cluster_hscale.md
  docs/user_docs/cli/kbcli_cluster_promote.md
  docs/user_docs/cli/kbcli_cluster_rebuild-instance.md
  docs/user_docs/cli/kbcli_cluster_restart.md
  docs/user_docs/cli/kbcli_cluster_start.md
  docs/user_docs/cli/kbcli_cluster_stop.md
  docs/user_docs/cli/kbcli_cluster_upgrade.md
  docs/user_docs/cli/kbcli_cluster_volume-expand.md
  docs/user_docs/cli/kbcli_cluster_vscale.md
  pkg/action/template/cluster_operations_template.cue
  pkg/action/template/opsrequest_template.cue
  pkg/cluster/charts/elasticsearch.tgz
  pkg/cluster/charts/kafka.tgz
  pkg/cluster/charts/mongodb.tgz
  pkg/cluster/charts/mysql.tgz
  pkg/cluster/charts/postgresql.tgz
  pkg/cluster/charts/qdrant.tgz
  pkg/cluster/helper.go
  pkg/cmd/cluster/cluster.go
  pkg/cmd/cluster/describe_ops.go
  pkg/cmd/cluster/describe_ops_test.go
  pkg/cmd/cluster/operations.go
  pkg/cmd/cluster/operations_test.go
  pkg/util/flags/flags.go
  pkg/util/flags/schema_to_flags.go
  pkg/util/util.go
Labels: size/XXL

#471 feat: playground only support k3d
  docs/user_docs/cli/kbcli_playground_init.md
  pkg/cmd/cluster/cluster_test.go
  pkg/cmd/cluster/create_subcmds.go
  pkg/cmd/cluster/create_subcmds_test.go
  pkg/cmd/playground/destroy.go
  pkg/cmd/playground/init.go
  pkg/cmd/playground/init_test.go
  pkg/cmd/playground/types.go
  pkg/testing/fake.go
Labels: size/L

#476 chore: adapt clusterDefinition commands
  docs/user_docs/cli/cli.md
  docs/user_docs/cli/kbcli_clusterdefinition.md
  pkg/cluster/cluster.go
  pkg/cluster/helper.go
  pkg/cmd/backuprepo/storageprovider.go
  pkg/cmd/cluster/cluster_test.go
  pkg/cmd/cluster/dataprotection.go
  pkg/cmd/clusterdefinition/clusterdefinition.go
  pkg/cmd/clusterdefinition/describe.go
  pkg/cmd/clusterdefinition/list_component_test.go
  pkg/cmd/clusterdefinition/list_components.go
  pkg/cmd/clusterdefinition/list_service_reference.go
  pkg/cmd/clusterdefinition/list_service_reference_test.go
  pkg/cmd/dataprotection/backuppolicy.go
  pkg/cmd/dataprotection/datatprotection_test.go
  pkg/cmd/dataprotection/restore.go
  pkg/testing/fake.go
  pkg/types/types.go
Labels: size/XL

#472 chore: playground only support k3d and aws
  docs/user_docs/cli/kbcli_playground_init.md
  pkg/cloudprovider/interface.go
  pkg/cloudprovider/types.go
  pkg/cluster/helper.go
  pkg/cmd/cluster/cluster_test.go
  pkg/cmd/cluster/operations.go
  pkg/cmd/playground/destroy.go
  pkg/cmd/playground/init.go
  pkg/cmd/playground/init_test.go
Labels: size/L
