Repository apecloud/kbcli, pull requests merged in 2024-09, with the labels that each got.

#435 fix: support create sharding cluster
  pkg/cmd/cluster/create_subcmds.go
  pkg/cmd/cluster/create_subcmds_test.go
Labels: size/M

#437 chore: adapt cluster connect command with 1.0 api
  docs/user_docs/cli/kbcli_cluster_connect.md
  go.mod
  go.sum
  pkg/cluster/cluster_chart.go
  pkg/cluster/helper.go
  pkg/cmd/cluster/connect.go
  pkg/cmd/cluster/connect_test.go
  pkg/cmd/cluster/describe.go
  pkg/cmd/cluster/logs.go
  pkg/cmd/cluster/logs_test.go
  pkg/cmd/cluster/operations_test.go
  pkg/testing/fake.go
Labels: size/XXL

#440 chore: delete deploy when upgrade
  docs/user_docs/cli/kbcli_kubeblocks_install.md
  docs/user_docs/cli/kbcli_kubeblocks_upgrade.md
  pkg/cmd/kubeblocks/compare.go
  pkg/cmd/kubeblocks/install.go
  pkg/cmd/kubeblocks/upgrade.go
  pkg/cmd/report/zipwritter.go
  pkg/preflight/analyzer/kb_taint.go
Labels: size/M

#446 chore: upgrade elasticsearch chart
  pkg/cluster/charts/elasticsearch-cluster.tgz
Labels: size/XS

#443 feat: restore-by-keys
  docs/user_docs/cli/kbcli_cluster_restore.md
  docs/user_docs/cli/kbcli_dataprotection_restore.md
  go.mod
  go.sum
  pkg/cmd/cluster/create.go
  pkg/cmd/cluster/dataprotection.go
  pkg/cmd/dataprotection/restore.go
  pkg/util/breakingchange/upgradehandlerto0.7.go
Labels: size/L, area/user-interaction

#442 feat: imporve cluster register and addon
  docs/user_docs/cli/kbcli_addon_install.md
  docs/user_docs/cli/kbcli_addon_search.md
  docs/user_docs/cli/kbcli_addon_upgrade.md
  docs/user_docs/cli/kbcli_cluster_register.md
  pkg/cluster/external_charts.go
  pkg/cluster/register_test.go
  pkg/cmd/addon/addon.go
  pkg/cmd/addon/install.go
  pkg/cmd/addon/install_test.go
  pkg/cmd/addon/search.go
  pkg/cmd/addon/search_test.go
  pkg/cmd/addon/uninstall.go
  pkg/cmd/addon/upgrade.go
  pkg/cmd/addon/util.go
  pkg/cmd/cluster/register.go
  pkg/cmd/cluster/register_test.go
  pkg/types/types.go
  pkg/util/helm/helm.go
Labels: size/XL

#450 chore: udpate Makefile on buiding embeding charts
  Makefile
Labels: size/M
