Repository apecloud/kbcli, pull requests merged in 2024-01, with the labels that each got.

#176 chore: support connect to Oracle
  go.mod
  go.sum
Labels: size/XS

#177 fix: invalid service annotations on gke
  pkg/action/template/cluster_operations_template.cue
  pkg/cmd/cluster/cluster.go
Labels: size/S

#179 fix: export AutoApprove field of OperationsOptions
  pkg/cmd/cluster/config_ops.go
  pkg/cmd/cluster/operations.go
  pkg/cmd/cluster/operations_test.go
Labels: size/M

#182 chore: promote add force option
  docs/user_docs/cli/kbcli_cluster_promote.md
  go.mod
  go.sum
  pkg/cmd/cluster/operations.go
Labels: size/XS

#183 chore: enable fetch addon
  Makefile
Labels: size/XS

#184 chore: enable fetch addon false
  .github/workflows/release-tag.yaml
Labels: size/XS

#186 feat: bench support redis benchmark
  docs/user_docs/cli/cli.md
  docs/user_docs/cli/kbcli_bench.md
  docs/user_docs/cli/kbcli_bench_redis-benchmark.md
  go.mod
  go.sum
  pkg/cmd/bench/bench.go
  pkg/cmd/bench/pgbench.go
  pkg/cmd/bench/redis-benchmark.go
  pkg/cmd/bench/sysbench.go
  pkg/cmd/bench/tpcc.go
  pkg/cmd/bench/tpch.go
  pkg/cmd/bench/ycsb.go
  pkg/types/types.go
Labels: size/L

#191 chore: addon uninstall support more than one addons
  docs/user_docs/cli/cli.md
  docs/user_docs/cli/kbcli_addon.md
  docs/user_docs/cli/kbcli_addon_install.md
  docs/user_docs/cli/kbcli_addon_search.md
  docs/user_docs/cli/kbcli_addon_uninstall.md
  pkg/cmd/addon/install.go
  pkg/cmd/addon/search.go
  pkg/cmd/addon/uninstall.go
Labels: size/M

#181 chore: refactor expose using new api
  go.mod
  go.sum
  pkg/action/template/cluster_operations_template.cue
  pkg/cmd/cluster/operations.go
  pkg/util/provider.go
  pkg/util/util.go
Labels: size/M

#199 chore: add new ops switchover
  pkg/cmd/cluster/operations.go
  pkg/cmd/cluster/operations_test.go
Labels: size/S

#201 fix: disable connect polardbx
  pkg/cmd/cluster/connect.go
  pkg/testing/fake.go
Labels: size/M

#206 fix: do custom switchover ops failed for ob
  pkg/cmd/cluster/operations.go
Labels: size/M

#211 fix: auto complete components failed for ops
  pkg/util/flags/flags.go
Labels: size/XS

#212 chore: support upgrade 0.6 to 0.8
  pkg/util/breakingchange/upgradehandlerto0.7.go
Labels: size/XS

#216 chore: oceanbase switchover
  pkg/cmd/cluster/operations.go
Labels: size/XS

#219 fix: upgrade 0.6 to 0.8 failed
  pkg/cmd/kubeblocks/upgrade.go
  pkg/util/helm/helm.go
Labels: size/S

#218 fix: fix connect nebula error
  pkg/cmd/cluster/connect.go
Labels: size/XS

#223 fix: upgrade 0.6 to 0.8 failed
  pkg/cmd/kubeblocks/install.go
  pkg/cmd/kubeblocks/upgrade.go
Labels: size/S

#220 feat: alert config
  pkg/cmd/alert/add_receiver.go
  pkg/cmd/alert/add_receiver_test.go
  pkg/cmd/alert/config_smtpserver.go
  pkg/cmd/alert/config_smtpserver_test.go
  pkg/cmd/alert/delete_receiver.go
  pkg/cmd/alert/delete_receiver_test.go
  pkg/cmd/alert/list_receivers.go
  pkg/cmd/alert/list_receivers_test.go
  pkg/cmd/alert/list_smtpserver.go
  pkg/cmd/alert/list_smtpserver_test.go
Labels: size/M

#229 chore: reset upgrade 0.6 to 0.8
  pkg/util/breakingchange/upgradehandlerto0.7.go
Labels: size/XS

#239 chore: upgrade kubeblocks to 0.8.0
  .github/workflows/cicd-pull-request.yml
  .github/workflows/cicd-push.yml
  Makefile
  go.mod
  go.sum
  pkg/cluster/charts/apecloud-mysql-cluster.tgz
  pkg/cluster/charts/clickhouse-cluster.tgz
  pkg/cluster/charts/elasticsearch-cluster.tgz
  pkg/cluster/charts/kafka-cluster.tgz
  pkg/cluster/charts/llm-cluster.tgz
  pkg/cluster/charts/milvus-cluster.tgz
  pkg/cluster/charts/mongodb-cluster.tgz
  pkg/cluster/charts/neon-cluster.tgz
  pkg/cluster/charts/oceanbase-cluster.tgz
  pkg/cluster/charts/postgresql-cluster.tgz
  pkg/cluster/charts/qdrant-cluster.tgz
  pkg/cluster/charts/redis-cluster.tgz
  pkg/cluster/charts/weaviate-cluster.tgz
  pkg/cluster/charts/xinference-cluster.tgz
Labels: size/S

#241 chore: fix lint
  .golangci.yaml
  docs/user_docs/cli/kbcli_cluster_create_redis.md
  pkg/cmd/accounts/base.go
  pkg/cmd/cluster/connect.go
  pkg/cmd/cluster/dataprotection_test.go
  pkg/cmd/cluster/logs.go
Labels: size/S

#242 chore: upgrade kubeblocks version to 0.8.1-beta.0
  go.mod
  go.sum
Labels: size/XS

#202 feat: check addon disable and uninstall
  docs/user_docs/cli/kbcli_addon_disable.md
  docs/user_docs/cli/kbcli_addon_uninstall.md
  pkg/cmd/addon/addon.go
  pkg/cmd/addon/uninstall.go
  pkg/cmd/addon/util.go
  pkg/cmd/addon/util_test.go
  pkg/testing/fake.go
  pkg/util/util.go
Labels: size/L

#243 chore: update driver setting according new api
  pkg/cmd/bench/redis-benchmark.go
  pkg/cmd/bench/sysbench.go
  pkg/cmd/bench/tpcc.go
Labels: size/XS

#246 fix: account mgr with componentDef err
  pkg/cluster/helper.go
Labels: size/XS

#251 fix: upgrade to 0.7.2 failed
  pkg/util/breakingchange/upgrader.go
Labels: size/XS
