Repository apecloud/kbcli, pull requests merged in 2024-05, with the labels that each got.

#327 chore: fix custom ops bug
  pkg/action/template/cluster_operations_template.cue
Labels: size/XS

#329 chore: show the recoverable time when describing the cluster
  go.mod
  go.sum
  pkg/cmd/cluster/config_observer.go
  pkg/cmd/cluster/dataprotection.go
  pkg/cmd/cluster/dataprotection_test.go
  pkg/cmd/cluster/delete_ops_test.go
  pkg/cmd/cluster/describe.go
  pkg/cmd/cluster/describe_ops.go
  pkg/cmd/cluster/describe_ops_test.go
  pkg/cmd/cluster/describe_test.go
  pkg/cmd/cluster/list_ops.go
  pkg/cmd/cluster/list_ops_test.go
  pkg/cmd/cluster/operations.go
  pkg/cmd/cluster/operations_test.go
  pkg/cmd/dataprotection/restore.go
  pkg/util/util.go
Labels: size/L

#330 fix: create custom ops failed
  pkg/action/template/cluster_operations_template.cue
Labels: size/XS

#328 fix: check if the specified backup method exists when creating a backup
  pkg/cmd/cluster/dataprotection.go
Labels: size/S

#334 fix: no cluster name when using list-ops cmd
  pkg/cmd/cluster/list_ops.go
Labels: size/XS

#336 fix: update the example in backuppolicy.go
  docs/user_docs/cli/kbcli_dataprotection_describe-backup-policy.md
  docs/user_docs/cli/kbcli_dataprotection_list-backup-policy.md
  pkg/cmd/dataprotection/backuppolicy.go
Labels: size/M

#338 chore: update kb version to 0.9.0-beta.20 (#332)
  go.mod
  go.sum
  pkg/cmd/cluster/config_diff.go
  pkg/cmd/cluster/config_edit.go
  pkg/cmd/cluster/config_observer.go
  pkg/cmd/cluster/config_ops.go
  pkg/cmd/cluster/update.go
  pkg/testing/fake.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: size/M

#340 chore: remove migration
  docs/user_docs/cli/cli.md
  docs/user_docs/cli/kbcli.md
  docs/user_docs/cli/kbcli_migration.md
  docs/user_docs/cli/kbcli_migration_create.md
  docs/user_docs/cli/kbcli_migration_describe.md
  docs/user_docs/cli/kbcli_migration_list.md
  docs/user_docs/cli/kbcli_migration_logs.md
  docs/user_docs/cli/kbcli_migration_templates.md
  docs/user_docs/cli/kbcli_migration_terminate.md
  pkg/cmd/cli.go
  pkg/cmd/migration/base.go
  pkg/cmd/migration/base_test.go
  pkg/cmd/migration/cmd_builder.go
  pkg/cmd/migration/cmd_builder_test.go
  pkg/cmd/migration/create.go
  pkg/cmd/migration/create_test.go
  pkg/cmd/migration/describe.go
  pkg/cmd/migration/describe_test.go
  pkg/cmd/migration/examples.go
  pkg/cmd/migration/list.go
  pkg/cmd/migration/list_test.go
  pkg/cmd/migration/logs.go
  pkg/cmd/migration/logs_test.go
  pkg/cmd/migration/suite_test.go
  pkg/cmd/migration/templates.go
  pkg/cmd/migration/templates_test.go
  pkg/cmd/migration/terminate.go
  pkg/cmd/migration/terminate_test.go
  pkg/types/migrationapi/migration_object_express.go
  pkg/types/migrationapi/migrationtask_types.go
  pkg/types/migrationapi/migrationtemplate_types.go
  pkg/types/migrationapi/type.go
  pkg/types/types.go
Labels: size/XXL

#339 fix: Raise the version constraint of KBCLI and KB (#300)
  pkg/cmd/version/version.go
  pkg/cmd/version/version_test.go
Labels: size/S

#342 chore: remove builder cmd
  docs/user_docs/cli/cli.md
  docs/user_docs/cli/kbcli.md
  docs/user_docs/cli/kbcli_builder.md
  docs/user_docs/cli/kbcli_builder_migrate-scripts.md
  docs/user_docs/cli/kbcli_builder_template.md
  pkg/cmd/builder/builder.go
  pkg/cmd/builder/builder_test.go
  pkg/cmd/builder/suite_test.go
  pkg/cmd/builder/template/component_wrapper.go
  pkg/cmd/builder/template/helm_helper.go
  pkg/cmd/builder/template/k8s_resource.go
  pkg/cmd/builder/template/mock_client.go
  pkg/cmd/builder/template/suite_test.go
  pkg/cmd/builder/template/template.go
  pkg/cmd/builder/template/template_test.go
  pkg/cmd/builder/template/util.go
  pkg/cmd/builder/tools/migrate_scripts.go
  pkg/cmd/cli.go
Labels: size/XXL

#343 chore: remove fault command
  docs/user_docs/cli/cli.md
  docs/user_docs/cli/kbcli.md
  docs/user_docs/cli/kbcli_fault.md
  docs/user_docs/cli/kbcli_fault_delete.md
  docs/user_docs/cli/kbcli_fault_io.md
  docs/user_docs/cli/kbcli_fault_io_attribute.md
  docs/user_docs/cli/kbcli_fault_io_errno.md
  docs/user_docs/cli/kbcli_fault_io_latency.md
  docs/user_docs/cli/kbcli_fault_io_mistake.md
  docs/user_docs/cli/kbcli_fault_list.md
  docs/user_docs/cli/kbcli_fault_network.md
  docs/user_docs/cli/kbcli_fault_network_bandwidth.md
  docs/user_docs/cli/kbcli_fault_network_corrupt.md
  docs/user_docs/cli/kbcli_fault_network_delay.md
  docs/user_docs/cli/kbcli_fault_network_dns.md
  docs/user_docs/cli/kbcli_fault_network_dns_error.md
  docs/user_docs/cli/kbcli_fault_network_dns_random.md
  docs/user_docs/cli/kbcli_fault_network_duplicate.md
  docs/user_docs/cli/kbcli_fault_network_http.md
  docs/user_docs/cli/kbcli_fault_network_http_abort.md
  docs/user_docs/cli/kbcli_fault_network_http_delay.md
  docs/user_docs/cli/kbcli_fault_network_http_patch.md
  docs/user_docs/cli/kbcli_fault_network_http_replace.md
  docs/user_docs/cli/kbcli_fault_network_loss.md
  docs/user_docs/cli/kbcli_fault_network_partition.md
  docs/user_docs/cli/kbcli_fault_node.md
  docs/user_docs/cli/kbcli_fault_node_detach-volume.md
  docs/user_docs/cli/kbcli_fault_node_restart.md
  docs/user_docs/cli/kbcli_fault_node_stop.md
  docs/user_docs/cli/kbcli_fault_pod.md
  docs/user_docs/cli/kbcli_fault_pod_failure.md
  docs/user_docs/cli/kbcli_fault_pod_kill-container.md
  docs/user_docs/cli/kbcli_fault_pod_kill.md
  docs/user_docs/cli/kbcli_fault_stress.md
  docs/user_docs/cli/kbcli_fault_time.md
  pkg/cmd/cli.go
  pkg/cmd/fault/fault.go
  pkg/cmd/fault/fault_constant.go
  pkg/cmd/fault/fault_dns.go
  pkg/cmd/fault/fault_dns_test.go
  pkg/cmd/fault/fault_http.go
  pkg/cmd/fault/fault_http_test.go
  pkg/cmd/fault/fault_io.go
  pkg/cmd/fault/fault_io_test.go
  pkg/cmd/fault/fault_network.go
  pkg/cmd/fault/fault_network_test.go
  pkg/cmd/fault/fault_node.go
  pkg/cmd/fault/fault_node_test.go
  pkg/cmd/fault/fault_pod.go
  pkg/cmd/fault/fault_pod_test.go
  pkg/cmd/fault/fault_stress.go
  pkg/cmd/fault/fault_stress_test.go
  pkg/cmd/fault/fault_time.go
  pkg/cmd/fault/fault_time_test.go
  pkg/cmd/fault/list_and_delete.go
  pkg/cmd/fault/list_and_delete_test.go
  pkg/cmd/fault/suite_test.go
Labels: size/XXL

#351 chore: update monitor-related and configconstraint api
  docs/user_docs/cli/kbcli_cluster_create.md
  docs/user_docs/cli/kbcli_cluster_update.md
  go.mod
  go.sum
  pkg/cmd/cluster/config_observer.go
  pkg/cmd/cluster/create.go
  pkg/cmd/cluster/dataprotection.go
  pkg/cmd/cluster/dataprotection_test.go
  pkg/cmd/cluster/describe_ops.go
  pkg/cmd/cluster/describe_ops_test.go
  pkg/cmd/cluster/update.go
  pkg/cmd/cluster/update_test.go
  pkg/cmd/playground/init.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: size/L

#354 chore: for merge update monitor-related and configconstraint api (#351)
  docs/user_docs/cli/kbcli_cluster_create.md
  docs/user_docs/cli/kbcli_cluster_create_mongodb.md
  docs/user_docs/cli/kbcli_cluster_create_mysql.md
  docs/user_docs/cli/kbcli_cluster_create_postgresql.md
  docs/user_docs/cli/kbcli_cluster_create_redis.md
  docs/user_docs/cli/kbcli_cluster_update.md
  go.mod
  go.sum
  pkg/cmd/cluster/config_observer.go
  pkg/cmd/cluster/create.go
  pkg/cmd/cluster/describe_ops.go
  pkg/cmd/cluster/describe_ops_test.go
  pkg/cmd/cluster/update.go
  pkg/cmd/cluster/update_test.go
  pkg/cmd/playground/init.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: size/L

#356 chore: optimize pod status display to be the same as kubectl get pod
  pkg/cluster/cluster.go
Labels: size/M

#358 chore: support convert configconstraint from v1alpha1 to v1beta1 (#357)
  pkg/cmd/kubeblocks/upgrade.go
  pkg/types/types.go
  pkg/util/breakingchange/upgrader.go
  pkg/util/conversion/conversion.go
  pkg/util/conversion/types.go
  pkg/util/conversion/utils.go
Labels: size/L

#359 chore: continuous backup's availablePod is not correct.
  pkg/cmd/cluster/dataprotection.go
Labels: size/XS
