Repository apecloud/kbcli, pull requests merged in 2024-03, with the labels that each got.

#279 chore: remove kbcli config subcommands dependence on clusterdefinition/clusterversion/componentdefinition (#277)
  pkg/cluster/helper.go
  pkg/cmd/cluster/config_ops.go
  pkg/cmd/cluster/config_ops_test.go
  pkg/cmd/cluster/config_resource.go
  pkg/cmd/cluster/config_util_test.go
  pkg/cmd/cluster/config_wrapper.go
  pkg/types/types.go
  pkg/util/util.go
Labels: size/XL

#283 fix: desc-config subcommand panic (#6773)
  pkg/cmd/cluster/config_observer.go
  pkg/cmd/cluster/list_ops.go
Labels: size/M

#284 chore: update kubeblocks version to kb-0.8.2-beta.17
  go.mod
  go.sum
  pkg/cmd/cluster/config_observer.go
Labels: size/S

#280 feat: edit-backup-policy supports backup encryption configuration
  docs/user_docs/cli/kbcli_cluster_edit-backup-policy.md
  go.mod
  go.sum
  pkg/cmd/builder/template/component_wrapper.go
  pkg/cmd/cluster/dataprotection.go
  pkg/cmd/cluster/dataprotection_test.go
Labels: size/L

#286 chore: fix release kbcli 0.7 error
  .github/workflows/release-create.yml
  .github/workflows/release-kbcli.yml
Labels: size/XS

#287 chore: ignore send msg release 0.7
  .github/workflows/release-kbcli.yml
Labels: size/XS

#282 chore: improve kbcli explain-config output
  pkg/cmd/cluster/config_util.go
Labels: size/S

#289 feat: support to run ops forcibly
  docs/user_docs/cli/kbcli_cluster_configure.md
  docs/user_docs/cli/kbcli_cluster_custom-ops.md
  docs/user_docs/cli/kbcli_cluster_edit-config.md
  docs/user_docs/cli/kbcli_cluster_expose.md
  docs/user_docs/cli/kbcli_cluster_hscale.md
  docs/user_docs/cli/kbcli_cluster_promote.md
  docs/user_docs/cli/kbcli_cluster_restart.md
  docs/user_docs/cli/kbcli_cluster_start.md
  docs/user_docs/cli/kbcli_cluster_stop.md
  docs/user_docs/cli/kbcli_cluster_upgrade.md
  docs/user_docs/cli/kbcli_cluster_volume-expand.md
  docs/user_docs/cli/kbcli_cluster_vscale.md
  pkg/action/template/cluster_operations_template.cue
  pkg/action/template/opsrequest_template.cue
  pkg/cmd/cluster/dataprotection.go
  pkg/cmd/cluster/operations.go
Labels: size/S

#291 feat: change according new bench api
  docs/user_docs/cli/kbcli_bench_pgbench.md
  docs/user_docs/cli/kbcli_bench_redis-benchmark.md
  docs/user_docs/cli/kbcli_bench_sysbench.md
  docs/user_docs/cli/kbcli_bench_tpcc.md
  docs/user_docs/cli/kbcli_bench_tpch.md
  docs/user_docs/cli/kbcli_bench_ycsb.md
  go.mod
  go.sum
  pkg/cmd/bench/bench.go
  pkg/cmd/bench/pgbench.go
  pkg/cmd/bench/redis-benchmark.go
  pkg/cmd/bench/sysbench.go
  pkg/cmd/bench/tpcc.go
  pkg/cmd/bench/tpch.go
  pkg/cmd/bench/ycsb.go
Labels: size/L

#293 chore: don not report error when the k8s provider is unknown
  pkg/cmd/cluster/operations.go
  pkg/util/util.go
Labels: size/XS

#294 chore: add "--path-prefix" flag to backuprepo create command
  docs/user_docs/cli/kbcli_backuprepo_create.md
  go.mod
  go.sum
  pkg/cmd/backuprepo/create.go
  pkg/cmd/cluster/config_observer.go
  pkg/testing/fake.go
Labels: size/M

#295 chore: support rebuild-instance cmd and update the customOps cmd
  docs/user_docs/cli/cli.md
  docs/user_docs/cli/kbcli_cluster.md
  pkg/action/create.go
  pkg/action/template/cluster_operations_template.cue
  pkg/cmd/cluster/cluster.go
  pkg/cmd/cluster/operations.go
Labels: size/L

#296 chore: update rebuild-instance cmd to new api
  go.mod
  go.sum
  pkg/action/template/cluster_operations_template.cue
  pkg/cmd/cluster/operations.go
  pkg/testing/fake.go
Labels: size/M
