Repository apecloud/kbcli, pull requests merged in 2024-12, with the labels that each got.

#505 chore: uninstall only remove crds that match label
  pkg/cmd/kubeblocks/kubeblocks_objects.go
  pkg/cmd/kubeblocks/kubeblocks_objects_test.go
Labels: size/S

#508 fix: addon enable only register the chart when addon type is engine
  pkg/cmd/addon/addon.go
Labels: size/XS

#511 fix: improve typo of list cmd in dataprotection
  docs/user_docs/cli/cli.md
  docs/user_docs/cli/kbcli_dataprotection.md
  docs/user_docs/cli/kbcli_dataprotection_backup.md
  docs/user_docs/cli/kbcli_dataprotection_list-backups.md
  pkg/cmd/dataprotection/actionset.go
  pkg/cmd/dataprotection/backup.go
  pkg/cmd/dataprotection/backuppolicy.go
  pkg/cmd/dataprotection/backuppolicytemplate.go
  pkg/cmd/dataprotection/datatprotection_test.go
  pkg/cmd/dataprotection/restore.go
Labels: size/M

#513 chore: support to create cluster with object flags
  pkg/cmd/cluster/create_subcmds.go
  pkg/cmd/cluster/create_util.go
  pkg/util/flags/flags.go
Labels: size/M

#509 chore: cluster restore support valid backup name
  pkg/cmd/dataprotection/restore.go
Labels: size/S

#512 feat: addon support clean sub-resource of multi-versions
  docs/user_docs/cli/cli.md
  docs/user_docs/cli/kbcli_addon.md
  pkg/cmd/addon/addon.go
  pkg/cmd/addon/delete_resource.go
  pkg/cmd/addon/delete_resource_test.go
  pkg/cmd/addon/uninstall.go
  pkg/cmd/addon/uninstall_test.go
Labels: size/XL

#516 feat: improve cluster list
  docs/user_docs/cli/kbcli_cluster_list.md
  pkg/action/list.go
  pkg/cluster/printer.go
  pkg/cmd/cluster/list.go
  pkg/cmd/cluster/list_test.go
Labels: size/L

#519 fix: create mongodb cluster failed
  docs/user_docs/cli/kbcli_cluster_create_elasticsearch.md
  docs/user_docs/cli/kbcli_cluster_create_kafka.md
  docs/user_docs/cli/kbcli_cluster_create_mongodb.md
  docs/user_docs/cli/kbcli_cluster_create_mysql.md
  docs/user_docs/cli/kbcli_cluster_create_postgresql.md
  docs/user_docs/cli/kbcli_cluster_create_qdrant.md
  docs/user_docs/cli/kbcli_cluster_create_redis.md
  pkg/cmd/cluster/create_subcmds.go
  pkg/cmd/cluster/create_util.go
Labels: size/M

#520 fix: make static bug
  pkg/cmd/trace/chart/reconciliation_trace_chart.go
  pkg/cmd/trace/chart/timeserieslinechart/timeserieslinechart.go
  pkg/cmd/trace/watch.go
Labels: size/S

#518 chore: addon install and search support auto complete
  docs/user_docs/cli/kbcli_addon_search.md
  pkg/cmd/addon/install.go
  pkg/cmd/addon/search.go
  pkg/cmd/addon/util.go
  pkg/cmd/addon/util_test.go
Labels: size/L

#522 chore: fix typo of cluster dp cmd
  docs/user_docs/cli/cli.md
  docs/user_docs/cli/kbcli_cluster.md
  docs/user_docs/cli/kbcli_cluster_backup.md
  docs/user_docs/cli/kbcli_cluster_list-backups.md
  pkg/cmd/cluster/dataprotection.go
Labels: size/M

#524 chore: support to upgrade addon to 1.0 when existing 0.9 addon
  go.mod
  go.sum
  pkg/cluster/external_charts.go
  pkg/cmd/addon/addon.go
  pkg/cmd/addon/upgrade.go
  pkg/cmd/cluster/operations.go
  pkg/cmd/kubeblocks/install_1.0.go
  pkg/types/types.go
Labels: size/L

#526 feat: support to convert cluster to v1 api version
  docs/user_docs/cli/cli.md
  docs/user_docs/cli/kbcli_cluster.md
  go.mod
  go.sum
  pkg/cmd/addon/addon.go
  pkg/cmd/cluster/cluster.go
  pkg/cmd/cluster/covert_to_1.0.go
  pkg/types/types.go
Labels: size/XL
