Repository apecloud/kbcli, pull requests merged in 2025-02, with the labels that each got.

#546 fix: switchover failed
  docs/user_docs/cli/kbcli_cluster_promote.md
  go.mod
  go.sum
  pkg/action/template/cluster_operations_template.cue
  pkg/cluster/cluster.go
  pkg/cmd/cluster/operations.go
  pkg/cmd/cluster/operations_test.go
  pkg/cmd/componentdefinition/describe.go
  pkg/testing/fake.go
Labels: size/L

#548 chore: release-kbcli.yml runs-on ubuntu-22.04
  .github/workflows/release-kbcli.yml
Labels: size/XS

#550 chore: upgrade artifact actions version 4
  .github/workflows/release-kbcli.yml
Labels: size/XS

#552 fix: get the highest priority role failed
  pkg/cmd/cluster/operations.go
Labels: size/S

#528 chore: add --no-diff flag for convert-to-1.0 cmd
  pkg/cmd/cluster/covert_to_1.0.go
Labels: size/XS

#556 chore: remove HALT in description and tests
  docs/user_docs/cli/kbcli_cluster_update.md
  go.mod
  go.sum
  pkg/action/create_test.go
  pkg/cluster/cluster_chart_test.go
  pkg/cmd/cluster/create_util_test.go
  pkg/cmd/cluster/update.go
Labels: size/M

#558 chore: update addons lists and subcommand docs
  Makefile
  docs/user_docs/cli/kbcli_addon_delete-resources-with-version.md
  docs/user_docs/cli/kbcli_alert.md
  docs/user_docs/cli/kbcli_alert_add-receiver.md
  docs/user_docs/cli/kbcli_alert_delete-receiver.md
  docs/user_docs/cli/kbcli_alert_list-receivers.md
  docs/user_docs/cli/kbcli_alert_list-smtpserver.md
  docs/user_docs/cli/kbcli_cluster_convert-to-v1.md
  docs/user_docs/cli/kbcli_cluster_create-account.md
  docs/user_docs/cli/kbcli_cluster_create.md
  docs/user_docs/cli/kbcli_cluster_create_apecloud-mysql.md
  docs/user_docs/cli/kbcli_cluster_create_clickhouse.md
  docs/user_docs/cli/kbcli_cluster_create_elasticsearch.md
  docs/user_docs/cli/kbcli_cluster_create_etcd.md
  docs/user_docs/cli/kbcli_cluster_create_kafak2.md
  docs/user_docs/cli/kbcli_cluster_create_kafka.md
  docs/user_docs/cli/kbcli_cluster_create_mongodb.md
  docs/user_docs/cli/kbcli_cluster_create_mysql.md
  docs/user_docs/cli/kbcli_cluster_create_oriol.md
  docs/user_docs/cli/kbcli_cluster_create_postgresql.md
  docs/user_docs/cli/kbcli_cluster_create_rabbitmq.md
  docs/user_docs/cli/kbcli_cluster_create_redis.md
  docs/user_docs/cli/kbcli_cluster_create_testredis.md
  docs/user_docs/cli/kbcli_cluster_create_xinference.md
  docs/user_docs/cli/kbcli_cluster_custom-ops.md
  docs/user_docs/cli/kbcli_cluster_delete-account.md
  docs/user_docs/cli/kbcli_cluster_grant-role.md
  docs/user_docs/cli/kbcli_cluster_hscale.md
  docs/user_docs/cli/kbcli_cluster_list-backup-policies.md
  docs/user_docs/cli/kbcli_cluster_list-backup-policy.md
  docs/user_docs/cli/kbcli_cluster_list-restores.md
  docs/user_docs/cli/kbcli_cluster_revoke-role.md
  docs/user_docs/cli/kbcli_clusterversion_list.md
  docs/user_docs/cli/kbcli_dataprotection_list-action-sets.md
  docs/user_docs/cli/kbcli_dataprotection_list-backup-policies.md
  docs/user_docs/cli/kbcli_dataprotection_list-backup-policy-templates.md
  docs/user_docs/cli/kbcli_dataprotection_list-backup-policy.md
  docs/user_docs/cli/kbcli_dataprotection_list-backup.md
  docs/user_docs/cli/kbcli_dataprotection_list-restore.md
  docs/user_docs/cli/kbcli_dataprotection_list-restores.md
  docs/user_docs/cli/kbcli_trace.md
  docs/user_docs/cli/kbcli_trace_create.md
  docs/user_docs/cli/kbcli_trace_delete.md
  docs/user_docs/cli/kbcli_trace_list.md
  docs/user_docs/cli/kbcli_trace_update.md
  docs/user_docs/cli/kbcli_trace_watch.md
  pkg/cluster/builtin_charts.go
  pkg/cluster/charts/apecloud-mysql.tgz
  pkg/cluster/charts/etcd.tgz
  pkg/cluster/charts/kafka.tgz
  pkg/cluster/charts/mongodb.tgz
  pkg/cluster/charts/mysql.tgz
  pkg/cluster/charts/postgresql.tgz
  pkg/cluster/charts/qdrant.tgz
  pkg/cluster/charts/rabbitmq.tgz
  pkg/cluster/charts/redis.tgz
Labels: size/XXL

#560 chore: default addon list update kbcli docs
  Makefile
  docs/user_docs/cli/kbcli_addon_delete-resources-with-version.md
  docs/user_docs/cli/kbcli_alert_add-receiver.md
  docs/user_docs/cli/kbcli_alert_delete-receiver.md
  docs/user_docs/cli/kbcli_alert_list-receivers.md
  docs/user_docs/cli/kbcli_cluster_convert-to-v1.md
  docs/user_docs/cli/kbcli_cluster_create-account.md
  docs/user_docs/cli/kbcli_cluster_create.md
  docs/user_docs/cli/kbcli_cluster_create_apecloud-mysql.md
  docs/user_docs/cli/kbcli_cluster_create_elasticsearch.md
  docs/user_docs/cli/kbcli_cluster_create_etcd.md
  docs/user_docs/cli/kbcli_cluster_create_kafka.md
  docs/user_docs/cli/kbcli_cluster_create_llm.md
  docs/user_docs/cli/kbcli_cluster_create_mongodb.md
  docs/user_docs/cli/kbcli_cluster_create_mysql.md
  docs/user_docs/cli/kbcli_cluster_create_oriol.md
  docs/user_docs/cli/kbcli_cluster_create_postgresql.md
  docs/user_docs/cli/kbcli_cluster_create_qdrant.md
  docs/user_docs/cli/kbcli_cluster_create_rabbitmq.md
  docs/user_docs/cli/kbcli_cluster_create_redis.md
  docs/user_docs/cli/kbcli_cluster_create_xinference.md
  docs/user_docs/cli/kbcli_cluster_custom-ops_kafka-quota.md
  docs/user_docs/cli/kbcli_cluster_custom-ops_kafka-topic.md
  docs/user_docs/cli/kbcli_cluster_custom-ops_kafka-user-acl.md
  docs/user_docs/cli/kbcli_cluster_custom-ops_mysql-orc-switchover.md
  docs/user_docs/cli/kbcli_cluster_delete-account.md
  docs/user_docs/cli/kbcli_cluster_list-backup-policies.md
  docs/user_docs/cli/kbcli_cluster_list-backup-policy.md
  docs/user_docs/cli/kbcli_cluster_list-restores.md
  docs/user_docs/cli/kbcli_clusterversion_list.md
  docs/user_docs/cli/kbcli_dataprotection_list-action-sets.md
  docs/user_docs/cli/kbcli_dataprotection_list-backup-policies.md
  docs/user_docs/cli/kbcli_dataprotection_list-backup-policy-templates.md
  docs/user_docs/cli/kbcli_dataprotection_list-backup-policy.md
  docs/user_docs/cli/kbcli_dataprotection_list-backup.md
  docs/user_docs/cli/kbcli_dataprotection_list-restore.md
  docs/user_docs/cli/kbcli_dataprotection_list-restores.md
  docs/user_docs/cli/kbcli_trace.md
  docs/user_docs/cli/kbcli_trace_create.md
  docs/user_docs/cli/kbcli_trace_delete.md
  docs/user_docs/cli/kbcli_trace_list.md
  docs/user_docs/cli/kbcli_trace_update.md
  docs/user_docs/cli/kbcli_trace_watch.md
  pkg/cluster/builtin_charts.go
  pkg/cluster/charts/apecloud-mysql.tgz
  pkg/cluster/charts/elasticsearch.tgz
  pkg/cluster/charts/etcd.tgz
  pkg/cluster/charts/kafka.tgz
  pkg/cluster/charts/llm.tgz
  pkg/cluster/charts/mongodb.tgz
  pkg/cluster/charts/mysql.tgz
  pkg/cluster/charts/postgresql.tgz
  pkg/cluster/charts/qdrant.tgz
  pkg/cluster/charts/rabbitmq.tgz
  pkg/cluster/charts/redis.tgz
  pkg/cluster/charts/xinference.tgz
Labels: size/XXL

#565 chore: remove enable-all-logs from kbcli update
  docs/user_docs/cli/kbcli_cluster_create.md
  docs/user_docs/cli/kbcli_cluster_create_qdrant.md
  docs/user_docs/cli/kbcli_cluster_create_rabbitmq.md
  docs/user_docs/cli/kbcli_cluster_custom-ops.md
  docs/user_docs/cli/kbcli_cluster_update.md
  pkg/cmd/cluster/list_logs.go
  pkg/cmd/cluster/update.go
  pkg/cmd/cluster/update_test.go
Labels: size/L

#571 chore: support to specified the backup namespace for restore
  docs/user_docs/cli/kbcli_cluster_restore.md
  go.mod
  go.sum
  pkg/cmd/cluster/dataprotection.go
Labels: size/XS

#572 fix: promote failed in multi-components
  pkg/cmd/cluster/operations.go
  pkg/cmd/cluster/operations_test.go
Labels: size/S

#569 fix: remove useless line
  pkg/cmd/cluster/create_subcmds.go
Labels: size/XS

#573 fix: fix ops expose
  docs/user_docs/cli/kbcli_cluster_expose.md
  pkg/cmd/cluster/operations.go
  pkg/util/util.go
Labels: size/M

#570 fix: improve cluster create comment
  docs/user_docs/cli/kbcli_cluster_create.md
  pkg/cmd/cluster/create.go
Labels: size/S

#576 chore: rename cmd delete_resource_with_version to purge for release-1.0
  docs/user_docs/cli/cli.md
  docs/user_docs/cli/kbcli_addon.md
  pkg/cmd/addon/addon.go
  pkg/cmd/addon/delete_resource.go
  pkg/cmd/addon/purge.go
  pkg/cmd/addon/purge_test.go
  pkg/cmd/addon/uninstall.go
  pkg/cmd/cluster/register_test.go
Labels: size/XL

#574 chore: delete dashboard cmd
  docs/user_docs/cli/cli.md
  docs/user_docs/cli/kbcli.md
  pkg/cmd/cli.go
  pkg/cmd/dashboard/dashboard.go
  pkg/cmd/dashboard/dashboard_test.go
  pkg/cmd/dashboard/grafana_direct.go
  pkg/cmd/dashboard/grafana_direct_test.go
  pkg/cmd/dashboard/suite_test.go
Labels: size/XL

#577 chore: delete dashboard cmd for 1.0
  docs/user_docs/cli/cli.md
  docs/user_docs/cli/kbcli.md
  pkg/cmd/cli.go
  pkg/cmd/dashboard/dashboard.go
  pkg/cmd/dashboard/dashboard_test.go
  pkg/cmd/dashboard/grafana_direct.go
  pkg/cmd/dashboard/grafana_direct_test.go
  pkg/cmd/dashboard/suite_test.go
Labels: size/XL
