Repository apecloud/kbcli, pull requests merged in 2025-05, with the labels that each got.

#602 fix: etcd null params
  docs/user_docs/cli/kbcli_cluster_create_etcd.md
  docs/user_docs/cli/kbcli_cluster_create_mongodb.md
  docs/user_docs/cli/kbcli_cluster_create_mysql.md
  docs/user_docs/cli/kbcli_cluster_create_rabbitmq.md
  pkg/cluster/charts/etcd.tgz
  pkg/cluster/charts/kafka.tgz
  pkg/cluster/charts/mongodb.tgz
  pkg/cluster/charts/mysql.tgz
  pkg/cluster/charts/postgresql.tgz
  pkg/cluster/charts/qdrant.tgz
  pkg/cluster/charts/rabbitmq.tgz
  pkg/cluster/charts/redis.tgz
  pkg/cmd/cluster/delete.go
  pkg/util/flags/flags.go
Labels: size/S

#604 fix: init playgroud bug
  docs/user_docs/cli/kbcli_cluster_describe-backup.md
  docs/user_docs/cli/kbcli_playground_init.md
  pkg/cloudprovider/k3d.go
  pkg/cmd/cluster/create_subcmds.go
  pkg/cmd/cluster/dataprotection.go
  pkg/cmd/playground/init.go
  pkg/cmd/playground/snapshot-controller/snapshot-controller-addon.yaml
  pkg/cmd/playground/snapshot-controller/snapshot-controller-cm.yaml
  pkg/cmd/playground/types.go
Labels: size/L

#605 fix: kbcli kb install failed
  pkg/cmd/kubeblocks/install.go
Labels: size/XS
