Repository apecloud/kbcli, pull requests merged in 2025-01, with the labels that each got.

#530 fix: edit-config subcommand does not take effect
  pkg/cmd/cluster/config_edit.go
Labels: size/S

#536 chore: update go.mod w.r.t trivy Severity
  go.mod
  go.sum
  pkg/cmd/trace/chart/summary/summary_chart.go
Labels: size/L

#534 fix: add enum check of flags of create cmd
  pkg/cmd/cluster/cluster_test.go
  pkg/cmd/cluster/create_subcmds.go
  pkg/cmd/cluster/create_subcmds_test.go
Labels: size/L

#532 fix: fix explain-config cmd
  pkg/cmd/cluster/config_observer.go
  pkg/cmd/cluster/errors.go
Labels: size/XS

#539 chore: tidy up promote and rebuild instance cmd with new api
  docs/user_docs/cli/kbcli_cluster_promote.md
  docs/user_docs/cli/kbcli_cluster_rebuild-instance.md
  go.mod
  go.sum
  pkg/action/template/cluster_operations_template.cue
  pkg/cmd/cluster/operations.go
  pkg/cmd/cluster/operations_test.go
Labels: size/L

#506 chore: remove rbac args
  docs/user_docs/cli/kbcli_cluster_create_elasticsearch.md
  docs/user_docs/cli/kbcli_cluster_delete.md
  pkg/cmd/cluster/create_util.go
  pkg/cmd/cluster/delete.go
Labels: size/M

#541 chore: deprecated reconfigure api field for kb-1.0
  pkg/action/template/cluster_operations_template.cue
Labels: size/M
