Repository apecloud/kbcli, pull requests merged in 2025-03, with the labels that each got.

#586 fix: switchover validate fail
  pkg/cmd/cluster/operations.go
  pkg/cmd/cluster/operations_test.go
Labels: size/S

#582 chore: cluster delete support force
  docs/user_docs/cli/kbcli_cluster_delete.md
  pkg/cmd/cluster/delete.go
  pkg/util/util.go
Labels: size/M

#589 fix: convert shard cluster failed
  pkg/cmd/cluster/covert_to_1.0.go
Labels: size/S

#590 chore: support reconfigure for kb 1.0 api
  Makefile
  docker/Dockerfile
  docs/user_docs/cli/cli.md
  docs/user_docs/cli/kbcli_cluster.md
  docs/user_docs/cli/kbcli_cluster_describe-config.md
  go.mod
  go.sum
  pkg/action/template/cluster_operations_template.cue
  pkg/cluster/cluster.go
  pkg/cmd/cluster/cluster.go
  pkg/cmd/cluster/config_diff.go
  pkg/cmd/cluster/config_edit.go
  pkg/cmd/cluster/config_observer.go
  pkg/cmd/cluster/config_ops.go
  pkg/cmd/cluster/config_ops_test.go
  pkg/cmd/cluster/config_resource.go
  pkg/cmd/cluster/config_util.go
  pkg/cmd/cluster/config_wrapper.go
  pkg/cmd/cluster/describe_ops.go
  pkg/cmd/cluster/errors.go
  pkg/cmd/cluster/list_ops.go
  pkg/cmd/cluster/logs_test.go
  pkg/printer/describe.go
  pkg/testing/fake.go
  pkg/types/types.go
  pkg/util/util.go
Labels: size/XXL

#591 fix: install 1.0 failed
  pkg/cmd/kubeblocks/install_1.0.go
  pkg/cmd/kubeblocks/status.go
Labels: size/S

#592 chore: rename convert_to_v1 to upgrade_to_v1
  docs/user_docs/cli/cli.md
  docs/user_docs/cli/kbcli_cluster.md
  pkg/cmd/cluster/cluster.go
  pkg/cmd/cluster/upgrade_to_1.0.go
Labels: size/M

#593 chore: update hcsshim version
  go.mod
  go.sum
Labels: size/S

#594 chore: install new 1.0 addon failed when existing 0.9 addon chart
  pkg/cmd/addon/install.go
  pkg/cmd/addon/upgrade.go
Labels: size/L

#595 chore: improve the diff format for upgrade-to-v1 command
  pkg/cmd/cluster/upgrade_to_1.0.go
Labels: size/XS
